# Generated by Django 3.2.7 on 2026-07-29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategories',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('title', models.CharField(
                    max_length=48, unique=True, verbose_name='Название')),
                ('min_lines', models.PositiveIntegerField(
                    verbose_name='Минимальное кол-во строк')),
                ('min_cognetive', models.PositiveIntegerField(
                    verbose_name='Минимальная когнитивная сложность')),
                ('max_cognetive', models.PositiveIntegerField(
                    default=9999,
                    verbose_name='Максимальная когнитивная сложность')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProjectForReview',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('github', models.URLField(verbose_name='GitHub')),
                ('comment', models.TextField(
                    default='Нет комментария',
                    verbose_name='Комментарий ученика')),
                ('status', models.BooleanField(
                    default=False, verbose_name='Проведено')),
                ('lines', models.PositiveIntegerField(
                    null=True, verbose_name='Кол-во строк')),
                ('cognetive', models.PositiveIntegerField(
                    null=True, verbose_name='Когнитивная сложность')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Отправлен')),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='project_review',
                    to='codereview.projectcategories',
                    verbose_name='Категория')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='code_reviews', to='Course.student',
                    verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Заявка на ревью',
                'verbose_name_plural': 'Заявки на ревью',
            },
        ),
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('problems',
                 ckeditor_uploader.fields.RichTextUploadingField(
                     blank=True, null=True, verbose_name='Проблемы')),
                ('amount_problems', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Всего проблем')),
                ('code_quality', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Общее качество кода')),
                ('code_architecture', models.PositiveIntegerField(
                    blank=True, null=True,
                    verbose_name='Уровень архитектуры')),
                ('code_standards', models.PositiveIntegerField(
                    blank=True, null=True,
                    verbose_name='Соблюдение стандартов языка')),
                ('code_principles', models.PositiveIntegerField(
                    blank=True, null=True,
                    verbose_name='Принципы программирования')),
                ('code_style', models.CharField(
                    blank=True,
                    choices=[
                        ('Маслёнок', 'Маслёнок'),
                        ('Маслёнок+', 'Маслёнок+'),
                        ('Маслёнок++', 'Маслёнок++'),
                        ('Pre-Junior', 'Pre-Junior'),
                        ('Junior', 'Junior'),
                        ('Junior+', 'Junior+'),
                        ('Middle', 'Middle'),
                    ],
                    default='Маслёнок', max_length=64, null=True,
                    verbose_name='Стиль разработки')),
                ('code_wishes', models.TextField(
                    blank=True, null=True, verbose_name='Общие пожелания')),
                ('status', models.BooleanField(
                    default=False, verbose_name='Пройдено')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Отправлено')),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='code_review',
                    to='codereview.projectforreview',
                    verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Ревью',
                'verbose_name_plural': 'Ревью',
            },
        ),
    ]
