# Generated by Django 3.2.7 on 2026-08-11 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codereview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Черновик сгенерирован'),
        ),
        migrations.AddField(
            model_name='codereview',
            name='ai_generation_error',
            field=models.TextField(blank=True, verbose_name='Ошибка генерации ИИ'),
        ),
        migrations.AddField(
            model_name='codereview',
            name='ai_generation_status',
            field=models.CharField(choices=[('not_requested', 'Не запрашивался'), ('generating', 'Генерируется'), ('ready', 'Черновик готов'), ('failed', 'Не удалось сформировать')], default='not_requested', max_length=16, verbose_name='Статус черновика ИИ'),
        ),
        migrations.AddField(
            model_name='codereview',
            name='ai_model',
            field=models.CharField(blank=True, max_length=64, verbose_name='Модель ИИ'),
        ),
        migrations.AddField(
            model_name='codereview',
            name='ai_source_summary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контекст для ИИ'),
        ),
        migrations.AddField(
            model_name='codereview',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Согласовано'),
        ),
        migrations.AddField(
            model_name='codereview',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_code_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Согласовал'),
        ),
        migrations.AddField(
            model_name='codereview',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать ученику'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codereview',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Показывать ученику'),
        ),
        migrations.AddField(
            model_name='codereview',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Черновик создан ИИ'),
        ),
    ]
