# Generated by Django 3.2.7 on 2024-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codereview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategories',
            name='min_lines',
        ),
        migrations.AlterField(
            model_name='projectcategories',
            name='max_lines',
            field=models.PositiveIntegerField(verbose_name='Максимальное кол-во строк'),
        ),
    ]
