# Generated by Django 3.2.7 on 2024-01-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codereview', '0002_auto_20240108_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectforreview',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий ученика'),
        ),
    ]
