# Generated by Django 5.2.17 on 2026-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codereview', '0002_auto_20260811_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='problems',
            field=models.TextField(blank=True, null=True, verbose_name='Проблемы'),
        ),
    ]
