# Generated by Django 3.2.7 on 2024-01-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codereview', '0004_alter_projectforreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectforreview',
            name='cognetive',
            field=models.PositiveIntegerField(null=True, verbose_name='Когнитивная сложность'),
        ),
        migrations.AlterField(
            model_name='projectforreview',
            name='lines',
            field=models.PositiveIntegerField(null=True, verbose_name='Кол-во строк'),
        ),
    ]
