# Generated by Django 3.2.7 on 2024-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codereview', '0005_auto_20240108_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategories',
            name='max_lines',
        ),
        migrations.AddField(
            model_name='projectcategories',
            name='min_lines',
            field=models.PositiveIntegerField(default=17, verbose_name='Минимальное кол-во строк'),
            preserve_default=False,
        ),
    ]
