# Generated by Django 3.2.7 on 2023-10-29 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=32, verbose_name='id платежа')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.student', verbose_name='Ученик')),
            ],
        ),
        migrations.CreateModel(
            name='InformationPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Course.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='EducationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Course.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Размер оплаты',
                'verbose_name_plural': 'Размеры оплат',
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Доп. занятие', 'Доп. занятие'), ('Индивидуальное занятие', 'Индивидуальное занятие'), ('Лекция', 'Лекция'), ('Пробное собеседование', 'Пробное собеседование'), ('Другое', 'Другое')], max_length=128, verbose_name='Причина')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Course.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Корректировка',
                'verbose_name_plural': 'Корректировки',
            },
        ),
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Course.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуски',
            },
        ),
    ]
