# Generated by Django 3.2.7 on 2023-02-22 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_absences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpayments',
            name='datetime',
        ),
        migrations.AddField(
            model_name='informationpayments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
