# Generated by Django 3.2.7 on 2023-02-22 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_alter_student_password'),
        ('billing', '0003_auto_20230222_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Доп. занятие', 'Доп. занятие'), ('Индивидуальное занятие', 'Индивидуальное занятие'), ('Лекция', 'Лекция'), ('Пробное собеседование', 'Пробное собеседование'), ('Другое', 'Другое')], max_length=128, verbose_name='Причина')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Course.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Корректировка',
                'verbose_name_plural': 'Корректировки',
            },
        ),
    ]
