# Generated by Django 3.2.7 on 2023-10-29 10:48

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('is_studies', models.BooleanField(default=False, verbose_name='Идут занятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Тема не задана!', max_length=128, verbose_name='Тема урока')),
                ('lesson_materials', ckeditor_uploader.fields.RichTextUploadingField(default='Дополнительных материалов нету!', verbose_name='Материалы к уроку')),
                ('lesson_type', models.CharField(choices=[('Практика', 'Практика'), ('Новая тема', 'Новая тема'), ('Ключевой урок', 'Ключевой урок')], default='Практика', max_length=64, verbose_name='Тип урока')),
                ('for_filter', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512, verbose_name='Вопрос')),
                ('solved', models.BooleanField(default=False, verbose_name='Решён')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Задан')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentquestion', to='Course.learngroup', verbose_name='Группа обучения')),
            ],
            options={
                'verbose_name': 'Вопрос ученика',
                'verbose_name_plural': 'Вопросы учеников',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('contact', models.CharField(max_length=128, verbose_name='Контакты')),
                ('email', models.EmailField(max_length=64, verbose_name='Почта')),
                ('password', models.CharField(default=2738, max_length=128, verbose_name='Пароль')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Учащийся')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегестрирован')),
                ('groups', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Course.learngroup', verbose_name='Группа обучения')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='ClassesTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='Понедельник', max_length=64, verbose_name='День недели')),
                ('time_lesson', models.TimeField(verbose_name='Время')),
                ('duration', models.TimeField(default='1:00:00', verbose_name='Продолжительность')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classtime', to='Course.learngroup', verbose_name='Группа обучения')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelesson', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Время занятия',
                'verbose_name_plural': 'Время занятий',
            },
        ),
        migrations.CreateModel(
            name='ApplicationsForTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Оставлена')),
                ('descry', models.BooleanField(default=False, verbose_name='Рассмотрена')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_training', to='Course.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Заявка на обучение',
                'verbose_name_plural': 'Заявки на обучение',
                'ordering': ('descry',),
            },
        ),
        migrations.CreateModel(
            name='AdditionalLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_lessons', to='Course.learngroup', verbose_name='Группа обучения')),
            ],
            options={
                'verbose_name': 'Сдвиг расписания',
                'verbose_name_plural': 'Сдвиг расписаний',
            },
        ),
    ]
