# Generated by Django 3.2.7 on 2023-02-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=5285, max_length=128, verbose_name='Пароль'),
        ),
    ]
