# Generated by Django 3.2.7 on 2023-02-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20230208_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=3107, max_length=128, verbose_name='Пароль'),
        ),
    ]
