# Generated by Django 3.2.7 on 2021-09-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20210917_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=96563426, max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.learngroup', verbose_name='Группа обучения'),
        ),
    ]
