# Generated by Django 3.1.7 on 2021-09-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_auto_20210917_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Course.learngroup', verbose_name='Группа обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=7991, max_length=128, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.DateField(verbose_name='День недели')),
                ('time_lesson', models.TimeField(verbose_name='Время')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.learngroup', verbose_name='Группа обучения')),
            ],
        ),
    ]
