# Generated by Django 3.2.7 on 2023-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=3127, max_length=128, verbose_name='Пароль'),
        ),
    ]
