# Generated by Django 3.2.7 on 2023-03-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_alter_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='group',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_display',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_lesson',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weekday',
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=8893, max_length=128, verbose_name='Пароль'),
        ),
    ]
