# Generated by Django 3.2.7 on 2021-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_auto_20210920_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lesson_materials',
            field=models.TextField(default='Дополнительных материалов нету!', verbose_name='Материалы к уроку'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=2297, max_length=128, verbose_name='Пароль'),
        ),
    ]
