# Generated by Django 3.2.7 on 2021-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_auto_20210924_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=6283, max_length=128, verbose_name='Пароль'),
        ),
    ]
