# Generated by Django 3.2.7 on 2023-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_auto_20230315_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='for_filter',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=7662, max_length=128, verbose_name='Пароль'),
        ),
    ]
