# Generated by Django 3.2.7 on 2023-05-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_auto_20230315_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=8014, max_length=128, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='AdditionalLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_lessons', to='Course.learngroup', verbose_name='Группа обучения')),
            ],
        ),
    ]
