# Generated by Django 3.2.7 on 2021-09-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=2240, max_length=128, verbose_name='Пароль'),
        ),
    ]
