# Generated by Django 3.2.7 on 2021-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='theme',
            field=models.CharField(default='Тема не задана!', max_length=128, verbose_name='Тема урока'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=1352, max_length=128, verbose_name='Пароль'),
        ),
    ]
