# Generated by Django 3.2.7 on 2021-09-24 20:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_auto_20210924_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson_materials',
            field=ckeditor.fields.RichTextField(default='Дополнительных материалов нету!', verbose_name='Материалы к уроку'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='theme',
            field=ckeditor.fields.RichTextField(default='Тема не задана!', max_length=128, verbose_name='Тема урока'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=6599, max_length=128, verbose_name='Пароль'),
        ),
    ]
