# Generated by Django 3.2.7 on 2021-09-27 13:51

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Course", "0011_auto_20210924_2049"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="absent",
            field=models.ManyToManyField(
                blank=True, null=True, to="Course.Student", verbose_name="Отсутствующие"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="key_topic",
            field=models.BooleanField(default=False, verbose_name="Ключевая тема"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_materials",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="Дополнительных материалов нету!",
                verbose_name="Материалы к уроку",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="groups",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="Course.learngroup",
                verbose_name="Группа обучения",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(default=7252, max_length=128, verbose_name="Пароль"),
        ),
    ]
