# Generated by Django 3.2.7 on 2021-09-26 13:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_auto_20210924_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='absent',
            field=models.ManyToManyField(null=True, to='Course.Student', verbose_name='Отсутствующие'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_materials',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Дополнительных материалов нету!', verbose_name='Материалы к уроку'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Course.learngroup', verbose_name='Группа обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=8271, max_length=128, verbose_name='Пароль'),
        ),
    ]
