# Generated by Django 3.2.7 on 2021-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0013_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='key_topic',
            field=models.BooleanField(default=False, verbose_name='Ключевая тема'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=7899, max_length=128, verbose_name='Пароль'),
        ),
    ]
