# Generated by Django 3.2.7 on 2021-09-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0014_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=2630, max_length=128, verbose_name='Пароль'),
        ),
    ]
