# Generated by Django 3.2.7 on 2021-09-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0014_auto_20210926_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='absent',
            field=models.ManyToManyField(blank=True, null=True, to='Course.Student', verbose_name='Отсутствующие'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=5698, max_length=128, verbose_name='Пароль'),
        ),
    ]
