# Generated by Django 3.2.7 on 2021-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Course", "0015_auto_20210929_1928"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="key_topic",
        ),
        migrations.AddField(
            model_name="schedule",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("Практика", "Практика"),
                    ("Новая тема", "Новая тема"),
                    ("Ключевой урок", "Ключевой урок"),
                ],
                default="Практика",
                max_length=64,
                verbose_name="Тип урока",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(default=4568, max_length=128, verbose_name="Пароль"),
        ),
    ]
