# Generated by Django 3.2.7 on 2021-09-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0015_auto_20210929_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='key_topic',
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson_type',
            field=models.CharField(choices=[('Практика', 'Практика'), ('Новая тема', 'Новая тема'), ('Ключевой урок', 'Ключевой урок')], default='Практика', max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=2678, max_length=128, verbose_name='Пароль'),
        ),
    ]
