# Generated by Django 3.2.7 on 2021-11-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_auto_20210926_1331'),
        ('Course', '0016_auto_20210930_1551'),
        ('Course', '0016_auto_20210930_1630'),
    ]

    operations = [
    ]
