# Generated by Django 3.2.7 on 2021-11-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0017_merge_20211121_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='absent',
            field=models.ManyToManyField(blank=True, null=True, to='Course.Student', verbose_name='Отсутствующие'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_type',
            field=models.CharField(choices=[('Практика', 'Практика'), ('Новая тема', 'Новая тема'), ('Ключевой урок', 'Ключевой урок')], default='Практика', max_length=64, verbose_name='Тип урока'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=7213, max_length=128, verbose_name='Пароль'),
        ),
    ]
