# Generated by Django 3.2.7 on 2021-11-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0018_auto_20211121_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=2569, max_length=128, verbose_name='Пароль'),
        ),
    ]
