# Generated by Django 5.2.17 on 2026-08-13 16:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_first_submissions(apps, schema_editor):
    LessonSolution = apps.get_model('Course', 'LessonSolution')
    LessonSolutionSubmission = apps.get_model(
        'Course',
        'LessonSolutionSubmission',
    )
    LessonSolutionSubmission.objects.bulk_create(
        [
            LessonSolutionSubmission(
                solution_id=solution.pk,
                attempt_number=1,
                submitted_at=solution.submitted_at,
            )
            for solution in LessonSolution.objects.only('pk', 'submitted_at')
        ],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0018_refine_foundations_and_interviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSolutionSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Номер попытки')),
                ('submitted_at', models.DateTimeField(db_index=True, verbose_name='Отправлено')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Course.lessonsolution', verbose_name='Решение урока')),
            ],
            options={
                'verbose_name': 'Отправка решения',
                'verbose_name_plural': 'История отправок решений',
                'ordering': ('-submitted_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('solution', 'attempt_number'), name='unique_solution_submission_attempt')],
            },
        ),
        migrations.RunPython(
            backfill_first_submissions,
            migrations.RunPython.noop,
        ),
    ]
