# Generated by Django 5.2.17 on 2026-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0019_lessonsolutionsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson_materials',
            field=models.TextField(default='Дополнительных материалов нету!', verbose_name='Материалы к уроку'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='plan',
            field=models.TextField(default='План не указан!', verbose_name='План урока'),
        ),
    ]
