# Generated by Django 3.2.7 on 2022-07-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0020_auto_20220715_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=7173, max_length=128, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512, verbose_name='Вопрос')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentquestion', to='Course.learngroup', verbose_name='Группа обучения')),
            ],
            options={
                'verbose_name': 'Вопрос ученика',
                'verbose_name_plural': 'Вопросы учеников',
            },
        ),
    ]
