# Generated by Django 5.2.17 on 2026-08-13 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0021_sync_active_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lesson_solution', 'Решение урока'), ('student_question', 'Вопрос ученика'), ('code_review', 'Проект на ревью')], max_length=24, verbose_name='Тип')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('target_url', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('event_key', models.CharField(editable=False, max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление преподавателя',
                'verbose_name_plural': 'Уведомления преподавателей',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='course_notify_unread_idx')],
            },
        ),
    ]
