# Generated by Django 5.2.17 on 2026-08-13 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0022_teachernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название версии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('archived', 'Архив')], default='draft', max_length=16, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий к версии')),
                ('base_signature', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликована')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curriculum_versions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_versions', to='Course.directionstudy', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Версия программы',
                'verbose_name_plural': 'Версии программы',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CurriculumLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.DecimalField(db_index=True, decimal_places=3, default=0, help_text='Можно использовать промежуточное значение, например 32,5.', max_digits=8, verbose_name='Порядок')),
                ('theme', models.CharField(max_length=128, verbose_name='Тема урока')),
                ('plan', models.TextField(verbose_name='План урока')),
                ('lesson_materials', models.TextField(verbose_name='Материалы к уроку')),
                ('lesson_type', models.CharField(choices=[('Практика', 'Практика'), ('Новая тема', 'Новая тема'), ('Ключевой урок', 'Ключевой урок')], default='Практика', max_length=64, verbose_name='Тип урока')),
                ('source_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_snapshots', to='Course.schedule', verbose_name='Опубликованный урок')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='Course.curriculumversion', verbose_name='Версия программы')),
            ],
            options={
                'verbose_name': 'Урок черновика программы',
                'verbose_name_plural': 'Уроки черновика программы',
                'ordering': ('version_id', 'position', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('direction',), name='one_draft_curriculum_per_direction'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('direction',), name='one_published_curriculum_per_direction'),
        ),
        migrations.AddIndex(
            model_name='curriculumlesson',
            index=models.Index(fields=['version', 'position'], name='course_draft_version_pos_idx'),
        ),
    ]
