# Generated by Django 3.2.7 on 2022-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0022_auto_20220720_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='solved',
            field=models.BooleanField(default=False, verbose_name='Решён'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=2557, max_length=128, verbose_name='Пароль'),
        ),
    ]
