# Generated by Django 5.2.17 on 2026-09-14 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0024_create_initial_curriculum_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Имя ученика')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=128, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='Откуда пришёл')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('call_scheduled', 'Назначен созвон'), ('call_completed', 'Созвон проведён'), ('awaiting_decision', 'Ожидает решения'), ('ready_to_start', 'Готов начать'), ('registered', 'Зарегистрирован'), ('studying', 'Обучается'), ('deferred', 'Отложил обучение'), ('declined', 'Отказался'), ('completed', 'Завершил обучение')], db_index=True, default='new', max_length=24, verbose_name='Статус')),
                ('current_level', models.TextField(blank=True, verbose_name='Текущий уровень')),
                ('previous_experience', models.TextField(blank=True, verbose_name='Предыдущий опыт')),
                ('learning_goals', models.TextField(blank=True, verbose_name='Цели обучения')),
                ('expectations', models.TextField(blank=True, verbose_name='Ожидания и пожелания')),
                ('schedule_preferences', models.TextField(blank=True, verbose_name='Предпочтения по расписанию')),
                ('time_commitment', models.TextField(blank=True, verbose_name='Время на самостоятельную работу')),
                ('concerns', models.TextField(blank=True, verbose_name='Сложности и опасения')),
                ('consultation_summary', models.TextField(blank=True, verbose_name='Итог первого созвона')),
                ('next_step', models.TextField(blank=True, verbose_name='Следующий шаг и договорённости')),
                ('next_contact_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Следующий контакт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_cards', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('desired_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospective_student_cards', to='Course.directionstudy', verbose_name='Желаемое направление')),
                ('responsible_teacher', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_student_cards', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный преподаватель')),
                ('student', models.OneToOneField(blank=True, help_text='Оставьте пустым до регистрации. После создания аккаунта выберите здесь соответствующего ученика.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_card', to='Course.student', verbose_name='Связанный ученик')),
            ],
            options={
                'verbose_name': 'Карточка ученика',
                'verbose_name_plural': 'Карточки учеников',
                'ordering': ('-updated_at', '-pk'),
                'permissions': (('view_all_student_cards', 'Может видеть все карточки учеников'),),
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('intro_call', 'Первый созвон'), ('lesson', 'Занятие'), ('feedback', 'Обратная связь'), ('organizational', 'Организационный вопрос'), ('other', 'Другое')], default='other', max_length=24, verbose_name='Тип записи')),
                ('text', models.TextField(verbose_name='Заметка')),
                ('next_step', models.TextField(blank=True, verbose_name='Следующий шаг')),
                ('remind_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Напомнить')),
                ('reminder_done', models.BooleanField(default=False, verbose_name='Напоминание выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Course.studentcard', verbose_name='Карточка ученика')),
            ],
            options={
                'verbose_name': 'Заметка по ученику',
                'verbose_name_plural': 'Заметки и созвоны',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
