# Generated by Django 3.2.7 on 2022-07-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20220702_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='questionnaire.answerquestion', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='questionnaire.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz', to='questionnaire.quiz', verbose_name='Опрос'),
        ),
    ]
