# Generated by Django 3.2.7 on 2022-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0012_auto_20220709_1538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.CharField(
                blank=True,
                default="Комментарий не добавлен!",
                max_length=750,
                verbose_name="Комментарий",
            ),
        ),
    ]
