# Generated by Django 3.2.7 on 2022-11-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_alter_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='answer',
            field=models.CharField(max_length=256, verbose_name='Ответ'),
        ),
    ]
