# Generated by Django 3.2.7 on 2022-11-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_alter_answerquestion_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['created_at'], 'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
    ]
