# Generated by Django 3.2.7 on 2023-01-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_alter_useranswer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
    ]
