# Generated by Django 3.2.14 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0017_alter_useranswer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Перенесён в архив",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="В архиве"),
        ),
    ]
