# Generated by Django 5.2.17 on 2026-08-13 16:08

from django.db import migrations, models


def backfill_answer_results(apps, schema_editor):
    AnswerQuestion = apps.get_model('questionnaire', 'AnswerQuestion')
    UserAnswer = apps.get_model('questionnaire', 'UserAnswer')
    for correct in (False, True):
        answer_ids = AnswerQuestion.objects.filter(correct=correct).values('pk')
        UserAnswer.objects.filter(answers_id__in=answer_ids).update(
            is_correct=correct,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_quiz_archive_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='Снимок результата в момент выбора ответа.', verbose_name='Ответ был правильным'),
        ),
        migrations.RunPython(
            backfill_answer_results,
            migrations.RunPython.noop,
        ),
    ]
