# Generated by Django 5.2 on 2026-08-22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questionnaire", "0019_useranswer_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="teachers_with_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Могут просматривать опрос и результаты, но не изменять его.",
                related_name="questionnaire_access",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватели с доступом",
            ),
        ),
    ]
