# Generated by Django 3.2.7 on 2023-10-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'ordering': ('-percent',), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='interviewquestioncategory',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
    ]
