# Generated by Django 3.2.7 on 2024-01-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20231031_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='complexity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Сложность'),
        ),
    ]
