"""
Django settings for CourseMC project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    """Read a conventional boolean value from the environment."""

    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=()):
    """Read a comma-separated environment variable without empty items."""

    value = os.environ.get(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]

try:
    from config import PROXYAPI_API_KEY as LOCAL_PROXYAPI_API_KEY
except ImportError:
    LOCAL_PROXYAPI_API_KEY = ''

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-development-only-change-me",
)
SOCIAL_AUTH_VK_OAUTH2_KEY = os.environ.get("SOCIAL_AUTH_VK_OAUTH2_KEY", "")
SOCIAL_AUTH_VK_OAUTH2_SECRET = os.environ.get(
    "SOCIAL_AUTH_VK_OAUTH2_SECRET",
    "",
)
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGIN_METHODS = {"username", "email"}

# Один и тот же секрет задаётся в окружении сайта и Telegram-бота. Значение
# намеренно не хранится в репозитории.
COURSEMC_BOT_API_TOKEN = os.environ.get("COURSEMC_BOT_API_TOKEN", "")

# Ключ хранится только в окружении сервера. Код-ревью продолжит работать и без
# него: заявка сохранится, а в админке появится причина, почему черновик ИИ не
# сформирован.
PROXYAPI_API_KEY = os.environ.get(
    "PROXYAPI_API_KEY",
    LOCAL_PROXYAPI_API_KEY,
)
PROXYAPI_REVIEW_MODEL = os.environ.get("PROXYAPI_REVIEW_MODEL", "gpt-4o-mini")
PROXYAPI_REVIEW_API_URL = os.environ.get(
    "PROXYAPI_REVIEW_API_URL",
    "https://api.proxyapi.ru/openai/v1/chat/completions",
)

# Preserve the primary key type used by the existing Django 3.2 migrations.
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    ("coursemc.ru", "www.coursemc.ru", "localhost", "127.0.0.1"),
)
CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    ("https://coursemc.ru", "https://www.coursemc.ru"),
)

# Nginx is the only published container and overwrites these proxy headers.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", True)
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
        True,
    )
    SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)

# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "CourseMC.apps.LocalizedPythonSocialAuthConfig",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "rest_framework",
    "colorfield",
    "reviews.apps.ReviewsConfig",
    "Course.apps.AuthConfig",
    "questionnaire.apps.QuestionnaireConfig",
    "blog.apps.BlogConfig",
    'py_interpreter.apps.PyInterpreterConfig',
    'chatgpt.apps.ChatgptConfig',
    'security.apps.SecurityConfig',
    'billing.apps.BillingConfig',
    'todolist.apps.TodolistConfig',
    'certificate.apps.CertificateConfig',
    'interview.apps.InterviewConfig',
    'codereview.apps.CodereviewConfig',
    'ai_assistant.apps.AiAssistantConfig',
]

UNFOLD = {
    "SITE_TITLE": "Курс M&C — админка",
    "SITE_HEADER": "Курс M&C",
    "SITE_SUBHEADER": "Управление учебной платформой",
    "SITE_SYMBOL": "school",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "CourseMC.admin_dashboard.dashboard_callback",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "BORDER_RADIUS": "8px",
    # App index pages inherit directly from ``admin/base.html`` and therefore
    # bypass the project's ``admin/base_site.html``. Register shared assets in
    # Unfold itself so the sidebar and row interactions stay styled on every
    # admin route, including application category pages.
    "STYLES": [
        lambda request: "/static/myadmins/admin_interactions.css",
    ],
    "SCRIPTS": [
        lambda request: "/static/myadmins/admin_row_navigation.js",
    ],
}

MIDDLEWARE = [
    "CourseMC.middleware.FilterIPMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "CourseMC.middleware.IPVisitorsMiddleware",
]

ROOT_URLCONF = "CourseMC.urls"

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "Course.context_processors.teacher_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "CourseMC.wsgi.application"

SOCIAL_AUTH_VK_OAUTH2_SCOPE = ["email"]

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("COURSEMC_DB_PATH", BASE_DIR / "db.sqlite3"),
        "OPTIONS": {
            "timeout": int(os.environ.get("COURSEMC_SQLITE_TIMEOUT", "20")),
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = (
    "social_core.backends.vk.VKOAuth2",  # бекенд авторизации через ВКонтакте
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
    "Course.auth_backends.StudentEmailAuthenticationBackend",
    # бекенд классической аутентификации, чтобы работала авторизация через обычный логин и пароль
)

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "bot_auth": "10/min",
    },
}

MEDIA_ROOT = os.environ.get("COURSEMC_MEDIA_ROOT", BASE_DIR / "media")
MEDIA_URL = "/media/"
PRIVATE_SOLUTION_MEDIA_ROOT = os.environ.get(
    "COURSEMC_PRIVATE_MEDIA_ROOT",
    BASE_DIR / "private_media" / "lesson_solutions",
)

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = os.environ.get("COURSEMC_STATIC_ROOT", BASE_DIR / "staticfiles")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "CourseMC/static"),
]

APPEND_SLASH = False

# Keep URL validation explicit ahead of Django 6.0's default change.
FORMS_URLFIELD_ASSUME_HTTPS = True

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
