# Generated by Django 3.2.7 on 2023-10-29 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('due_date', models.DateField(default='2023-10-29', verbose_name='Дата')),
                ('created_at', models.DateField(default='2023-10-29', verbose_name='Создано')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolist.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='TodoListUser',
            fields=[
                ('todolist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist.todolist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская',
                'verbose_name_plural': 'Пользовательские',
                'ordering': ['-created_at'],
            },
            bases=('todolist.todolist',),
        ),
        migrations.CreateModel(
            name='TodoListGroup',
            fields=[
                ('todolist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist.todolist')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.learngroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Групповая',
                'verbose_name_plural': 'Групповые',
                'ordering': ['-created_at'],
            },
            bases=('todolist.todolist',),
        ),
    ]
