# Generated by Django 3.2.7 on 2024-01-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20240108_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(default='2024-01-09', verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2024-01-09', verbose_name='Дата'),
        ),
    ]
