# Generated by Django 3.2.7 on 2022-07-25 07:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Текст поста"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(max_length=256, verbose_name="Описание"),
        ),
    ]
