# Generated by Django 3.2.7 on 2022-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_displayed",
            field=models.BooleanField(default=False, verbose_name="Отображается"),
        ),
    ]
