# Generated by Django 3.2.7 on 2022-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="posts", to="blog.Category", verbose_name="Категории"
            ),
        ),
    ]
