# Generated by Django 3.2.7 on 2022-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                upload_to="uploads/blog/%Y/%m/%d", verbose_name="Изображение"
            ),
        ),
    ]
