# Generated by Django 3.2.7 on 2022-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="uploads/blog/default.jpeg",
                upload_to="uploads/blog/%Y/%m/%d",
                verbose_name="Изображение",
            ),
        ),
    ]
