# Generated by Django 3.2.7 on 2023-10-29 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=64, verbose_name='Имя фамилия')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('comment', models.TextField(default='', verbose_name='Рекомендация')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Course.student', unique=True, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
